show_rating_text field added
simplygoodsoftware/pyrusservicedesk pull request #106
Opened 2023-02-20 14:38 UTC by AlexSukhobrusov

добавлено: поле show_rating_text типа String
логика: теперь будет приходить поле show_rating_text вместе с show_rating и мы отображаем show_rating_text в виде отдельного комментария

https://pyrus.com/t#id110714240

2023-02-21 09:22 UTC, BoyarinMax requested changes

2023-02-21 09:22 UTC, BoyarinMax commented on PyrusServiceDeskAndroid/pyrusservicedesk/src/main/java/com/pyrus/pyrusservicedesk/presentation/ui/navigation_page/ticket/TicketViewModel.kt
> +            if (freshList.showRating) {
&& showRatingText.notBlank()

2023-02-27 09:47 UTC, AlexSukhobrusov commented on PyrusServiceDeskAndroid/pyrusservicedesk/src/main/java/com/pyrus/pyrusservicedesk/presentation/ui/navigation_page/ticket/TicketViewModel.kt
> +            if (freshList.showRating) {
done

2023-02-28 10:49 UTC, BoyarinMax approved these changes

2023-03-17 10:35 UTC, merged