External auth
simplygoodsoftware/pyrusservicedesk pull request #45
Opened 2020-10-15 13:52 UTC by VitalyKuznetsov

2020-10-15 14:38 UTC, BoyarinMax requested changes
а где драфт чистится?

2020-10-15 14:38 UTC, BoyarinMax commented on PyrusServiceDeskAndroid/pyrusservicedesk/src/main/java/com/pyrus/pyrusservicedesk/sdk/RequestFactory.kt
> +    fun getSetPushTokenRequest(token: String?): RequestBase<Unit> {
Добавь коммент почему  токен может быть нуловым

2020-10-19 06:59 UTC, BoyarinMax requested changes

2020-10-19 06:59 UTC, BoyarinMax commented on PyrusServiceDeskAndroid/servicedesksample/src/main/java/com/pyrus/servicedesksample/SampleApp.java
> +                "24Ed4oIBtoeHnqDHNU5O7zLeOILVziiMP2pkghQZAL1SXHztt0w8HSv5u9LNGitjNR~pU3JOLPGt3jq-1jwwDUjJzgqlvV3TpyDyD8Bq72clDyhWyOrW8lr9lf4yfrwt0tb80w==",
это лучше убрать

2020-10-19 07:00 UTC, BoyarinMax commented
а где драфты затираются?

2020-10-20 08:39 UTC, VitalyKuznetsov commented on PyrusServiceDeskAndroid/servicedesksample/src/main/java/com/pyrus/servicedesksample/SampleApp.java
> +                "24Ed4oIBtoeHnqDHNU5O7zLeOILVziiMP2pkghQZAL1SXHztt0w8HSv5u9LNGitjNR~pU3JOLPGt3jq-1jwwDUjJzgqlvV3TpyDyD8Bq72clDyhWyOrW8lr9lf4yfrwt0tb80w==",
Убрал

2020-10-20 08:39 UTC, VitalyKuznetsov commented
> а где драфт чистится?

Добавил, см в initIternal

2020-10-20 08:54 UTC, BoyarinMax commented
влей мастер

2020-10-20 08:54 UTC, BoyarinMax approved these changes

2020-10-20 09:51 UTC, merged