fix interval time
simplygoodsoftware/pyrusservicedesk pull request #46
Opened 2020-10-16 12:08 UTC by BoyarinMax

2020-10-16 13:39 UTC, VitalyKuznetsov requested changes
То есть если ни разу не заходил на экран, не будет апдейта?

2020-10-16 13:39 UTC, VitalyKuznetsov commented on PyrusServiceDeskAndroid/servicedesksample/src/main/java/com/pyrus/servicedesksample/SampleApp.java
> +                "24Ed4oIBtoeHnqDHNU5O7zLeOILVziiMP2pkghQZAL1SXHztt0w8HSv5u9LNGitjNR~pU3JOLPGt3jq-1jwwDUjJzgqlvV3TpyDyD8Bq72clDyhWyOrW8lr9lf4yfrwt0tb80w=="
?

2020-10-16 13:47 UTC, BoyarinMax commented on PyrusServiceDeskAndroid/servicedesksample/src/main/java/com/pyrus/servicedesksample/SampleApp.java
> +                "24Ed4oIBtoeHnqDHNU5O7zLeOILVziiMP2pkghQZAL1SXHztt0w8HSv5u9LNGitjNR~pU3JOLPGt3jq-1jwwDUjJzgqlvV3TpyDyD8Bq72clDyhWyOrW8lr9lf4yfrwt0tb80w=="
поправил

2020-10-16 13:47 UTC, BoyarinMax commented
> То есть если ни разу не заходил на экран, не будет апдейта?

да

2020-10-19 08:28 UTC, VitalyKuznetsov approved these changes

2020-10-19 11:53 UTC, merged