custom ui
simplygoodsoftware/pyrusservicedesk pull request #62
Opened 2020-12-07 07:56 UTC by BoyarinMax

custom ui for Ivi

2020-12-07 09:45 UTC, VitalyKuznetsov requested changes

2020-12-07 09:45 UTC, VitalyKuznetsov commented on PyrusServiceDeskAndroid/pyrusservicedesk/src/main/res/values/colors.xml
> +    <color name="psd_comment_preview_outline">#40D9D9D9</color>
Тоже дизайн?

2020-12-07 09:45 UTC, VitalyKuznetsov commented on PyrusServiceDeskAndroid/pyrusservicedesk/src/main/res/values-v29/styles.xml
> +<!--        <item name="android:forceDarkAllowed">true</item>-->
Может тогда просто убрать?

2020-12-07 09:45 UTC, VitalyKuznetsov commented on PyrusServiceDeskAndroid/pyrusservicedesk/src/main/res/layout/psd_activity_file_preview.xml
> +        android:visibility="visible">
Можно убрать?

2020-12-07 09:45 UTC, VitalyKuznetsov commented on PyrusServiceDeskAndroid/pyrusservicedesk/src/main/java/com/pyrus/pyrusservicedesk/utils/ConfigUtils.kt
> +         * @param context Activity context.
А не Application?

2020-12-07 09:45 UTC, VitalyKuznetsov commented on PyrusServiceDeskAndroid/pyrusservicedesk/src/main/java/com/pyrus/pyrusservicedesk/utils/ConfigUtils.kt
> +        fun getSupportMessageTextColor(context: Context, backgroundColor: Int): Int {
Напиши коммент, что за backgroundColor

2020-12-07 09:45 UTC, VitalyKuznetsov commented on PyrusServiceDeskAndroid/pyrusservicedesk/src/main/java/com/pyrus/pyrusservicedesk/utils/ConfigUtils.kt
> +            return getColor(context.applicationContext, colorRes)
Можнт тогда сразу просить applicationContext?

2020-12-07 09:45 UTC, VitalyKuznetsov commented on PyrusServiceDeskAndroid/pyrusservicedesk/src/main/java/com/pyrus/pyrusservicedesk/presentation/ui/view/swiperefresh/DirectedSwipeRefresh.java
> +     * @param color Resource id of the color.
Мб, лучше colorId? + пометить @ resId

2020-12-07 09:45 UTC, VitalyKuznetsov commented on PyrusServiceDeskAndroid/pyrusservicedesk/src/main/java/com/pyrus/pyrusservicedesk/presentation/ui/navigation_page/ticket/TicketActivity.kt
> +        supportActionBar?.apply { title = "" }
А нельзя у него в layout убрать текст, а тут не трогать?

2020-12-07 12:28 UTC, BoyarinMax commented on PyrusServiceDeskAndroid/pyrusservicedesk/src/main/res/values-v29/styles.xml
> +<!--        <item name="android:forceDarkAllowed">true</item>-->
сделал переключалку

2020-12-07 12:28 UTC, BoyarinMax commented on PyrusServiceDeskAndroid/pyrusservicedesk/src/main/res/layout/psd_activity_file_preview.xml
> +        android:visibility="visible">
ага

2020-12-07 12:28 UTC, BoyarinMax commented on PyrusServiceDeskAndroid/pyrusservicedesk/src/main/java/com/pyrus/pyrusservicedesk/utils/ConfigUtils.kt
> +         * @param context Activity context.
не, все верно

2020-12-07 12:28 UTC, BoyarinMax commented on PyrusServiceDeskAndroid/pyrusservicedesk/src/main/java/com/pyrus/pyrusservicedesk/utils/ConfigUtils.kt
> +            return getColor(context.applicationContext, colorRes)
не, очень много лишнего кода появится, и даже если сюда попадет applicationContext вызов у него applicationContext вернет его самого

2020-12-07 12:28 UTC, BoyarinMax commented on PyrusServiceDeskAndroid/pyrusservicedesk/src/main/java/com/pyrus/pyrusservicedesk/presentation/ui/view/swiperefresh/DirectedSwipeRefresh.java
> +     * @param color Resource id of the color.
это @ColorInt

2020-12-07 12:28 UTC, BoyarinMax commented on PyrusServiceDeskAndroid/pyrusservicedesk/src/main/java/com/pyrus/pyrusservicedesk/presentation/ui/navigation_page/ticket/TicketActivity.kt
> +        supportActionBar?.apply { title = "" }
нельзя

2020-12-07 12:28 UTC, BoyarinMax commented on PyrusServiceDeskAndroid/pyrusservicedesk/src/main/java/com/pyrus/pyrusservicedesk/utils/ConfigUtils.kt
> +        fun getSupportMessageTextColor(context: Context, backgroundColor: Int): Int {
ok

2020-12-07 12:28 UTC, BoyarinMax commented on PyrusServiceDeskAndroid/pyrusservicedesk/src/main/java/com/pyrus/pyrusservicedesk/ServiceDeskConfiguration.kt
> +         * The custom font family.
ждем мнения эксперта.

2020-12-07 12:57 UTC, VitalyKuznetsov requested changes

2020-12-07 12:57 UTC, VitalyKuznetsov commented on PyrusServiceDeskAndroid/pyrusservicedesk/src/main/java/com/pyrus/pyrusservicedesk/presentation/ui/navigation_page/ticket/TicketActivity.kt
> +        supportActionBar?.apply { title = "" }
Напиши коммент, плиз
Что он автоматом проставляет значение, поэтому мы должны каждый раз тут менять

2020-12-07 12:57 UTC, VitalyKuznetsov commented on PyrusServiceDeskAndroid/pyrusservicedesk/src/main/java/com/pyrus/pyrusservicedesk/utils/ConfigUtils.kt
> +        fun getSupportMessageTextColor(context: Context, backgroundColor: Int): Int {
В смысле напиши, зачем он нужен, плиз

2020-12-07 13:08 UTC, BoyarinMax commented on PyrusServiceDeskAndroid/pyrusservicedesk/src/main/java/com/pyrus/pyrusservicedesk/presentation/ui/navigation_page/ticket/TicketActivity.kt
> +        supportActionBar?.apply { title = "" }
done

2020-12-07 13:08 UTC, BoyarinMax commented on PyrusServiceDeskAndroid/pyrusservicedesk/src/main/java/com/pyrus/pyrusservicedesk/utils/ConfigUtils.kt
> +        fun getSupportMessageTextColor(context: Context, backgroundColor: Int): Int {
job done my lord

2020-12-08 08:04 UTC, VitalyKuznetsov approved these changes

2020-12-15 12:26 UTC, merged