Mb/new token timeout
simplygoodsoftware/pyrusservicedesk pull request #82
Opened 2021-12-14 14:37 UTC by BoyarinMax

2021-12-14 20:49 UTC, AlexSukhobrusov requested changes
Влей #81 ПР плз

2021-12-16 07:10 UTC, BoyarinMax commented on PyrusServiceDeskAndroid/servicedesksample/src/main/java/com/pyrus/servicedesksample/SampleApp.java
> +                "ghfghfghf",
)))))

2022-01-11 13:03 UTC, AlexSukhobrusov requested changes
Исправь и можешь вливать

2022-01-11 13:03 UTC, AlexSukhobrusov commented on PyrusServiceDeskAndroid/pyrusservicedesk/src/main/java/com/pyrus/pyrusservicedesk/PyrusServiceDesk.kt
> +            while (timeList.size >= 5) {
5 в константу

2022-01-11 13:11 UTC, merged